version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn odev.wsgi:application --bind 0.0.0.0:8000
    container_name: crypto
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app/.env
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"

volumes:
  postgres_data: