# Generated by Django 4.2.5 on 2023-09-22 13:19

import django.core.validators
from django.db import migrations, models

import cryptocurrency.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('ETH', 'Ethereum')], default='ETH', max_length=3),
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.CharField(default=cryptocurrency.utils.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
