# Generated by Django 4.2.5 on 2023-09-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_wallet_balance_wallet_currency_wallet_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
